package org.openapitools.codegen.mustacle.example.lomb;

import java.util.List;
import lombok.Data;

@Data
public class ResponsesItem{
	private boolean isModel;
	private boolean hasMultipleTypes;
	private boolean hasHeaders;
	private List<Object> requiredVars;
	private boolean isBooleanSchemaTrue;
	private boolean isAnyType;
	private boolean isInteger;
	private boolean isNumber;
	private boolean isDecimal;
	private List<Object> vars;
	private boolean exclusiveMinimum;
	private boolean isShort;
	private boolean isUnboundedInteger;
	private boolean simpleType;
	private boolean isPassword;
	private boolean hasDiscriminatorWithNonEmptyMapping;
	private String complexType;
	private String dataType;
	private boolean isBinary;
	private boolean isUuid;
	private boolean isMap;
	private boolean additionalPropertiesIsAnyType;
	private boolean isDefault;
	private List<Object> responseHeaders;
	private boolean is2xx;
	private boolean is4xx;
	private boolean isNumeric;
	private boolean uniqueItems;
	private boolean isEmail;
	private boolean isArray;
	private boolean isBooleanSchemaFalse;
	private boolean hasRequired;
	private boolean isDouble;
	private Schema schema;
	private String code;
	private boolean range;
	private boolean hasValidation;
	private Content content;
	private String baseType;
	private boolean wildcard;
	private boolean exclusiveMaximum;
	private boolean isBoolean;
	private String jsonSchema;
	private boolean isDate;
	private boolean isString;
	private boolean primitiveType;
	private boolean isFreeFormObject;
	private List<Object> headers;
	private VendorExtensions vendorExtensions;
	private boolean isLong;
	private boolean isFile;
	private boolean isEnum;
	private boolean schemaIsFromAdditionalProperties;
	private boolean isFloat;
	private boolean isPrimitiveType;
	private String message;
	private boolean hasVars;
	private boolean isByteArray;
	private boolean isVoid;
	private boolean is3xx;
	private boolean is5xx;
	private boolean isDateTime;
	private boolean isNull;
	private boolean is1xx;
	private String containerTypeMapped;
	private Items items;
	private String containerType;
}