package org.openapitools.codegen.mustacle.example.lomb;

import java.util.List;
import lombok.Data;

@Data
public class Response{
	private String modelSrcPath;
	private String appVersion;
	private String generatorClass;
	private boolean sortParamsByRequiredFlag;
	private String operationTagDescription;
	private String invokerPackage;
	private String classVarName;
	private boolean generateModelDocs;
	private boolean hasImport;
	private boolean generateModelTests;
	private boolean strictSpecBehavior;
	private boolean generateApiTests;
	private String classFilename;
	private Lambda lambda;
	private boolean generateModels;
	private String apiVersion;
	private String inputSpec;
	private String artifactUrl;
	private String developerOrganization;
	private String baseName;
	private String jsonMemberPackage;
	private List<ImportsItem> imports;
	private String contextPath;
	private String appDescription;
	private String licenseName;
	private String interfaceNamePrefix;
	private String version;
	private String releaseNote;
	private License license;
	private String modelDocPath;
	private String escapedInvokerPackage;
	private String abstractNameSuffix;
	private String srcBasePath;
	private String testBasePath;
	private String importPath;
	private String generatedYear;
	private String modelPackage;
	private String abstractNamePrefix;
	private String gitHost;
	private String apiSrcPath;
	private String apiTestPath;
	private String apiDocPath;
	private String licenseInfo;
	private boolean hasModel;
	private boolean generateApis;
	private String basePathWithoutHost;
	private String primitives;
	private String developerOrganizationUrl;
	private Operations operations;
	private String interfaceNameSuffix;
	private String packageName;
	private boolean hideGenerationTimestamp;
	private String modelTestPath;
	private String unescapedAppDescription;
	private String appName;
	private boolean generateApiDocs;
	private String generatorVersion;
	private String traitNameSuffix;
	private String apiPackage;
	private String basePath;
	private String classname;
	private String gitRepoId;
	private String generatedDate;
	private String traitNamePrefix;
	private String appDescriptionWithNewLines;
	private String gitUserId;
}